### ISSUE TITLE
ESP-Now Burst necessary for RTCM?

### ISSUE THREAD

**Issue by bobzwik** [yuri-rage/ESP-Now-Burst-Serial-Bridge#1]
Hello! I've been looking around for code for Mavlink over ESP32, and I'm glad I've found your code. I saw that you have 2 versions of your code, simple ESP-Now and ESP-Now Burst, stating that RTCM3 messages are over the 250 byte limit of ESP-Now. 

Having a look at the Mavlink messages, I've found [GPS_RTCM_DATA ](https://mavlink.io/en/messages/common.html#GPS_RTCM_DATA), which is fragmented in 182 byte packets. If this is the message needed for RTK corrections, then shouldn't your simple ESP-Now code be sufficient?

To clarify my application, I'm planning to use ESP-Now between 2 drones. Drone1 receives RTCM corrections from the base station using classic RFD900 radios, but forwards those messages to Drone2. Drone2 sends it's position to Drone1, for Drone1 to follow Drone2.

I'm attempting to use ESP32 to try and lower the latency between the 2 drones. Using RFD900s to communication between the 2 drones, I would get 160ms of delay.

I'm just wondering if you had an opinion on this, if you think I am wrong about the GPS_RTCM_DATA message and than I will be requiring to use your ESP-Now Burst. I'll be trying it out anyways this week (or the next).

Thanks!

John

**Comment by bobzwik** [comment]
Nevermind, I though this repo was for Mavlink communication WITH RCTM corrections. I now understand that this is for ONLY RTCM transmission from GPS to GPS (instead of from GCS to Ardupilot). Sorry.

I've tried RTK over Mavlink with your ESP-Now Serial bridge code, between 2 drones, and it works!! But the connection drops sometimes, mostly when trying to download params of Drone2 (which have to go through Drone1 to get to Mission Planner).

**Comment by yuri-rage** [comment]
You answered your own question before I had a chance.

MAVLink messages rarely if ever exceed the ESP-Now payload limit. Actual RTCM3 messages are a completely different story, hence this variation of the serial bridge.

Closing the issue.
